### ISSUE TITLE
Issue on page /recursion.html

### ISSUE THREAD

**Issue by RaymondFriend** [28left/descriptive_set_theory#13]
Extra "ist" after definition of infimum near beginning

**Comment by RaymondFriend** [comment]
$\alpha$ in first paragraph should be $\xi$

**Comment by RaymondFriend** [comment]
$V$ should be bolded in the proof of the Recursion on Ordinals Theorem.

**Comment by 28left** [comment]
Fixed by 93d3e69ca6ebb964d0ec08ff44390b52f6be767d
