### ISSUE TITLE
Issue on page /constructible.html

### ISSUE THREAD

**Issue by RaymondFriend** [28left/descriptive_set_theory#19]
- Typo in formula for Vbl(a): get rid of "=" in "x=\in ω "
- In section "definability of definability", the formula capturing $P_{Def}(a)$, should the model be (a, \in), not (a,e)? 
- (H3) in definition of cumulative hierarchy is missing a condition about α < λ

**Comment by 28left** [comment]
Fixed in f12163d7c09885ab525bf8a094a6623419dee248

**Comment by 28left** [comment]
Fixed in 3f770c65ddf1afc138de361dcfb66fcd86f99e91
