### ISSUE TITLE
Issue on page /projective.html

### ISSUE THREAD

**Issue by RaymondTana** [28left/descriptive_set_theory#6]
When defining the projective hierarchy (boldface), you wrote that $\Sigma^1_{n+1}(X) = \exists^{\N^\N} \Sigma^1_1(X)$, but should repalce the final class with $\Pi^1_n(X)$.

**Comment by RaymondFriend** [comment]
When stating basic equivalent definitions for the first few classes, the line for $\Pi^1_1$ should use the set $G$, not $F$.

**Comment by 28left** [comment]
Fixed in eda2dc410670843ef4b5036cf1391631815194a1
